---
title: "New Year's Eve Data Exploration"
output:
  html_document: default
  pdf_document: default
message: FALSE
warning: FALSE

date: "2023-03-01"
---

<!--Setup-->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!--Load packages-->
```{r include=FALSE}
# Load packages
library(dplyr)
library(tidyverse)
library(scales)
library(data.table)

```

<!--Input-->
<!--Load the data-->
```{r include=FALSE}
# Define the list of cities and file names
cities <- c("ams", "london", "paris", "rome")
filenames <- paste0("listings-", cities, ".csv.gz")

# Loop through each city and read in the data
for (i in seq_along(cities)) {
  # Read in the listings data
  assign(paste0("list_", cities[i]),read_csv(gzfile(paste0('../../data/',filenames[i]))))
  
  # Read in the calendar data
  assign(paste0("cal_", cities[i]), read_csv(gzfile(paste0('../../data/',"calendar-", cities[i], ".csv.gz"))))
}
```

<!--Transformation-->
<!--subset lists of the city from the listing data-->
```{r, echo=FALSE}
#subset lists of the city from the listing data
subset_list_ams <- data.frame(
  id = list_ams$id,
  host_id = list_ams$host_id,
  host_location = list_ams$host_location,
  neighbourhood = list_ams$neighbourhood,
  room_type = list_ams$room_type,
  price = list_ams$price,
  minimum_nights = list_ams$minimum_nights,
  beds = list_ams$beds,
  city = "Amsterdam"
)

subset_list_london <- data.frame(
  id = list_london$id,
  host_id = list_london$host_id,
  host_location= list_london$host_location,
  neighbourhood = list_london$neighbourhood,
  room_type = list_london$room_type,
  price = list_london$price,
  minimum_nights = list_london$minimum_nights,
  beds = list_london$beds,
  city = "London"
)

subset_list_paris <- data.frame(
  id = list_paris$id,
  host_id = list_paris$host_id,
  host_location = list_paris$host_location,
  neighbourhood = list_paris$neighbourhood,
  room_type = list_paris$room_type,
  price = list_paris$price,
  minimum_nights = list_paris$minimum_nights,
  beds = list_paris$beds,
  city = "Paris")

subset_list_rome <- data.frame(
  id = list_rome$id,
  host_id = list_rome$host_id,
  host_location = list_rome$host_location,
  neighbourhood = list_rome$neighbourhood,
  room_type = list_rome$room_type,
  price = list_rome$price,
  minimum_nights = list_rome$minimum_nights,
  beds = list_rome$beds,
  city = "Rome")

total_list <- rbind(subset_list_ams, subset_list_london, subset_list_paris, subset_list_rome)

```


```{r, echo=FALSE}
##subset lists of the city from the calendar data
subset_cal_ams <- data.frame(
  listing_id = cal_ams$listing_id,
  date = cal_ams$date,
  available = cal_ams$available,
  city = "Amsterdam"
)

subset_cal_london <- data.frame(
  listing_id = cal_london$listing_id,
  date = cal_london$date,
  available = cal_london$available,
  city = "London"
)

subset_cal_paris <- data.frame(
  listing_id = cal_paris$listing_id,
  date = cal_paris$date,
  available = cal_paris$available,
  city = "Paris"
)

subset_cal_rome <- data.frame(
  listing_id = cal_rome$listing_id,
  date = cal_rome$date,
  available = cal_rome$available,
  city = "Rome"
)

total_cal <- rbind(subset_cal_ams, subset_cal_london, subset_cal_paris, subset_cal_rome)

```


<!--Output-->
<!--Table outputs-->
**Summary statistics on the price of the cities for the listings dataset**
```{r, echo = FALSE, message=FALSE, warning=FALSE}
prices_cities <- total_list %>%
  select ("price", "city")

price_summary <- data.table(na.omit(prices_cities))
price_summary[, price := gsub('[$]', '', price) %>% as.numeric(as.character(price))]
price_summary <- price_summary[price > 0]
price_summary <- price_summary[, .(min_price = min(price), mean_price = mean(price), 
                                   max_price = max(price)), by = city]

# display the price summary table
price_summary

```

**Summary statistics for beds per city**
```{r, echo = FALSE, message=FALSE, warning=FALSE}
beds_cities <- total_list %>%
  select("beds", "city")

beds_summary <- data.table(na.omit(beds_cities))
beds_summary <- beds_summary[, .(min_beds = min(beds), mean_beds = mean(beds), 
                                   max_beds = max(beds)), by = city]

beds_summary
```

**Airbnb listings availability per city between the 5th of December 2022 and the 4th of December 2023** 
```{r, echo=FALSE}
total_cal <- total_cal %>% 
  mutate(available = ifelse(available == TRUE, "available", available)) %>%
  mutate(available = ifelse(available == FALSE, "unavailable", available))

table(total_cal$available,  total_cal$city)
```

**Number of rooms types per city**
```{r, echo=FALSE}
table(total_list$room_type, total_list$city)
```

**Room types in Amsterdam (%)**
```{r, echo=FALSE}
Amsterdam <- table(list_ams$room_type)
prop.table(Amsterdam)
```

**Room types in London (%)**
```{r, echo=FALSE}
London <- table(list_london$room_type)
prop.table(London)
```

**Room types in Paris (%)**
```{r, echo=FALSE}
Paris <- table(list_paris$room_type)
prop.table(Paris)
```

**Room types in Rome (%)**
```{r, echo=FALSE}
Rome <- table(list_rome$room_type)
prop.table(Rome)
```

<!--Piechart outputs-->
```{r, echo=FALSE}
piepercent_ams<- round(100*table(list_ams$room_type)/sum(table(list_ams$room_type)), 1)
pie(table(list_ams$room_type), labels = paste0(piepercent_ams, "%"), main = "Airbnb room types offered in Amsterdam", col = rainbow(length(table(list_ams$room_type)), s = 0.5))
legend("bottomleft", c("Entire home/apt","Hotel room","Private room","Shared room"), cex = 0.8,
       fill = rainbow(length(table(list_ams$room_type)), s = 0.5))
```


```{r, echo=FALSE}
piepercent_london<- round(100*table(list_london$room_type)/sum(table(list_london$room_type)), 1)
pie(table(list_london$room_type), labels = paste0(piepercent_london, "%"), main = "Airbnb room types offered in London", col = rainbow(length(table(list_london$room_type)), s = 0.5))
legend("bottomright", c("Entire home/apt","Hotel room","Private room","Shared room"), cex = 0.8,
       fill = rainbow(length(table(list_london$room_type)), s = 0.5))
```


```{r, echo=FALSE}
piepercent_paris<- round(100*table(list_paris$room_type)/sum(table(list_paris$room_type)), 1)
pie(table(list_paris$room_type), labels = paste0(piepercent_paris, "%"), main = "Airbnb room types offered in Paris", col = rainbow(length(table(list_paris$room_type)), s = 0.5))
legend("bottomleft", c("Entire home/apt","Hotel room","Private room","Shared room"), cex = 0.8,
       fill = rainbow(length(table(list_paris$room_type)), s = 0.5))
```


```{r, echo=FALSE}
piepercent_rome<- round(100*table(list_rome$room_type)/sum(table(list_rome$room_type)), 1)
pie(table(list_rome$room_type), labels = paste0(piepercent_rome, "%"), main = "Airbnb room types offered in Rome", col = rainbow(length(table(list_rome$room_type)), s = 0.5))
legend("topright", c("Entire home/apt","Hotel room","Private room","Shared room"), cex = 0.8,
       fill = rainbow(length(table(list_rome$room_type)), s = 0.5))
```

<!--Bargraph outputs-->
```{r, echo=FALSE}
ggplot(list_ams, aes(x = room_type)) +
  geom_bar(aes(fill = room_type), position = "dodge") +
  ggtitle("Amsterdam") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Type of room", y = "Number of rooms", title="Quantity of type of rooms in Amsterdam", fill = "Type of room") +
  scale_fill_viridis_d()
```


```{r, echo=FALSE}
ggplot(list_london, aes(x = room_type)) +
  geom_bar(aes(fill = room_type), position = "dodge") +
  ggtitle("London") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Type of room", y = "Number of rooms", title="Quantity of type of rooms in London", fill = "Type of room") +
  scale_fill_viridis_d()
```


```{r, echo=FALSE}
ggplot(list_paris, aes(x = room_type)) +
  geom_bar(aes(fill = room_type), position = "dodge") +
  ggtitle("Paris") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Type of room", y = "Number of rooms", title="Quantity of type of rooms in Paris", fill = "Type of room") +
  scale_fill_viridis_d()
```


```{r, echo=FALSE}
ggplot(list_rome, aes(x = room_type)) +
  geom_bar(aes(fill = room_type), position = "dodge") +
  ggtitle("Rome") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Type of room", y = "Number of rooms", title="Quantity of type of rooms in Rome", fill = "Type of room") +
  scale_fill_viridis_d()
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(list_ams, aes(x = room_type)) +
  geom_bar(aes(y = (..count..)/sum(..count..), fill = room_type), position = "dodge") +
  ggtitle("Amsterdam") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Type of room", y = "Number of rooms", title="Percentage of rooms offered in Amsterdam", fill = "Type of room") +
  scale_fill_viridis_d() +
  scale_y_continuous(labels = scales::percent_format(), name = "Percentage of rooms")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(list_london, aes(x = room_type)) +
  geom_bar(aes(y = (..count..)/sum(..count..), fill = room_type), position = "dodge") +
  ggtitle("London") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Type of room", y = "Number of rooms", title="Percentage of rooms offered in London", fill = "Type of room") +
  scale_fill_viridis_d() +
  scale_y_continuous(labels = scales::percent_format(), name = "Percentage of rooms")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(list_paris, aes(x = room_type)) +
  geom_bar(aes(y = (..count..)/sum(..count..), fill = room_type), position = "dodge") +
  ggtitle("Paris") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Type of room", y = "Number of rooms", title="Percentage of rooms offered in Paris", fill = "Type of room") +
  scale_fill_viridis_d() +
  scale_y_continuous(labels = scales::percent_format(), name = "Percentage of rooms")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(list_rome, aes(x = room_type)) +
  geom_bar(aes(y = (..count..)/sum(..count..), fill = room_type), position = "dodge") +
  ggtitle("Rome") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Type of room", y = "Number of rooms", title="Percentage of rooms offered in Rome", fill = "Type of room") +
  scale_fill_viridis_d() +
  scale_y_continuous(labels = scales::percent_format(), name = "Percentage of rooms")
```


```{r, echo=FALSE}
ggplot(total_list, aes(x = room_type)) +
  geom_bar(aes(fill = room_type), position = "dodge") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  facet_grid(~city) +
  labs(x = "Type of room", y = "Number of rooms", title="Number and type of rooms comparison between the cities", fill = "Type of room") +
  scale_fill_viridis_d()
par(mar = c(0.1, 0.1, 0.1, 0.1))
```
